ALTER TABLE waitlist
ADD COLUMN createdatetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE service_offered
ADD COLUMN createdatetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE waitlist_service
ADD COLUMN createdatetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;