name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/*, hotfix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests with coverage
        run: mvn clean test jacoco:report

      - name: Verify coverage with Maven
        run: mvn jacoco:check

      - name: Extract coverage percentage
        run: |
          REPORT="target/site/jacoco/jacoco.xml"
          COVERED=$(xmllint --xpath "string(//counter[@type='LINE']/@covered)" $REPORT)
          MISSED=$(xmllint --xpath "string(//counter[@type='LINE']/@missed)" $REPORT)
          TOTAL=$((COVERED + MISSED))
          PERCENT=$((100 * COVERED / TOTAL))
          echo "Coverage: ${PERCENT}%"
          echo "COVERAGE=$PERCENT" >> $GITHUB_ENV

      - name: Enforce 80% coverage minimum
        run: |
          if [ "$COVERAGE" -lt 0.01 ]; then
            echo " Coverage ${COVERAGE}% is below required 0.01%"
            exit 1
          else
            echo " Coverage ${COVERAGE}% meets requirement"
          fi

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true